name: ci_publish

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test with devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            poetry install
            poetry run ./lint.sh
            poetry run ./test.sh

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: test
    if: github.ref_type == 'tag'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.3

      - name: Build with devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            echo ${GITHUB_REF/refs\/tags\//}
            tag=${GITHUB_REF/refs\/tags\//}
            poetry version $tag
            poetry install
            poetry build
            poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
